# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'index.js'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy index.js'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: index-js
    targetPath: '$(Build.ArtifactStagingDirectory)/index.js'
    publishLocation: 'pipeline'
  displayName: 'Publish index.js artifact'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: 
